/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MeetingIndexRouteImport } from './routes/meeting/index'
import { Route as MeetingPesanRuanganRouteImport } from './routes/meeting/pesan-ruangan'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIndexRoute = MeetingIndexRouteImport.update({
  id: '/meeting/',
  path: '/meeting/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingPesanRuanganRoute = MeetingPesanRuanganRouteImport.update({
  id: '/meeting/pesan-ruangan',
  path: '/meeting/pesan-ruangan',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRoute
  '/meeting/pesan-ruangan': typeof MeetingPesanRuanganRoute
  '/meeting': typeof MeetingIndexRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRoute
  '/meeting/pesan-ruangan': typeof MeetingPesanRuanganRoute
  '/meeting': typeof MeetingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRoute
  '/meeting/pesan-ruangan': typeof MeetingPesanRuanganRoute
  '/meeting/': typeof MeetingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/dashboard' | '/meeting/pesan-ruangan' | '/meeting'
  fileRoutesByTo: FileRoutesByTo
  to: '/dashboard' | '/meeting/pesan-ruangan' | '/meeting'
  id: '__root__' | '/dashboard' | '/meeting/pesan-ruangan' | '/meeting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRoute
  MeetingPesanRuanganRoute: typeof MeetingPesanRuanganRoute
  MeetingIndexRoute: typeof MeetingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/': {
      id: '/meeting/'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/pesan-ruangan': {
      id: '/meeting/pesan-ruangan'
      path: '/meeting/pesan-ruangan'
      fullPath: '/meeting/pesan-ruangan'
      preLoaderRoute: typeof MeetingPesanRuanganRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRoute,
  MeetingPesanRuanganRoute: MeetingPesanRuanganRoute,
  MeetingIndexRoute: MeetingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
